version: "3.1"
services:

    db:
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      container_name: "${PROJECT_NAME}-mysql"
      env_file:
        - .env
      volumes:
        - ./.mdata:/var/lib/mysql
      ports:
        - "8306:3306"

    webserver:
      image: nginx:alpine
      container_name: "${PROJECT_NAME}-webserver"
      volumes:
          - ./app:/var/www/html
          - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
# Next lines can be uncommented for basic auth and self-singed HTTPS
#          - ./phpdocker/nginx/.htpasswd:/etc/nginx/conf.d/.htpasswd
#          - ./phpdocker/nginx/keys:/etc/nginx/keys
      ports:
       - "${SITE_PORT}:80"
#       - "${SECURE_SITE_PORT}:443"
      depends_on:
       - fpm

    fpm:
      image: markvortman/smlaravel:latest
      container_name: "${PROJECT_NAME}-fpm"
      volumes:
        - ./app:/application

    mailhog:
      image: mailhog/mailhog
      container_name: "${PROJECT_NAME}-mailhog"
      ports:
        - "1025:1025"
        - "${MAILHOG_WEB_PORT}:8025"